CREATE TABLE IF NOT EXISTS users (
  id SERIAL PRIMARY KEY,
  username VARCHAR(100) Not NULL UNIQUE,
  firstname VARCHAR(64),
  lastname VARCHAR(64),
  role VARCHAR(32) NOT NULL DEFAULT 'user',
  password VARCHAR(255) NOT NULL
);